version: 2.1
executors:
  exectr:
    docker:
      - image: glyphrider/erlang:latest

jobs:
  build:
    executor: exectr
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            erlc -DTEST roman.erl
            erlc -DTEST roman_tests.erl
      - persist_to_workspace:
          root: .
          paths: .

  test:
    executor: exectr
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            erl -noinput -run roman_tests verbose_testing -s init stop
      - store_test_results:
          path: .

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
