version: 2.1
executors:
  erlang-latest:
    docker:
      - image: library/erlang:latest

jobs:
  compile-and-test:
    executor: erlang-latest
    steps:
      - checkout
      - run:
          name: Compile code
          command: |
            mkdir -pv ebin
            erlc -DTEST -o ebin src/roman.erl
            erlc -DTEST -o ebin src/roman_tests.erl
      - run:
          name: Execute eunit
          command: |
            erl -pz ebin -noinput -run roman verbose_testing -s init stop
      - store_test_results:
          path: .
      - store_artifacts:
          path: TEST-roman.xml

workflows:
  version: 2
  compile-and-test:
    jobs:
      - compile-and-test
